import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans bg-mainbackground">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-mainbackground antialiased`}
      >
        {/* {<SessionProvider session={session}>{children} </SessionProvider>} */}

        <header></header>

        <main className="w-full flex justify-center">{children}</main>
      </body>
    </html>
  );
}
