export const principleYouArchetypeList = [
  {title: 'Adventurer', value: 'adventurer'},
  {title: 'Artisan', value: 'artisan'},
  {title: 'Campaigner', value: 'campaigner'},
  {title: 'Coach', value: 'coach'},
  {title: 'Commander', value: 'commander'},
  {title: 'Critic', value: 'critic'},
  {title: 'Enforcer', value: 'enforcer'},
  {title: 'Entertainer', value: 'entertainer'},
  {title: 'Explorer', value: 'explorer'},
  {title: 'Growth Seeker', value: 'growthSeeker'},
  {title: 'Helper', value: 'helper'},
  {title: 'Implementer', value: 'implementer'},
  {title: 'Impresario', value: 'impresario'},
  {title: 'Individualist', value: 'individualist'},
  {title: 'Inspirer', value: 'inspirer'},
  {title: 'Inventor', value: 'inventor'},
  {title: 'Investigator', value: 'investigator'},
  {title: 'Orchestrator', value: 'orchestrator'},
  {title: 'Peacekeeper', value: 'peacekeeper'},
  {title: 'Planner', value: 'planner'},
  {title: 'Problem Solver', value: 'problemSolver'},
  {title: 'Promoter', value: 'promoter'},
  {title: 'Protector', value: 'protector'},
  {title: 'Quiet Leader', value: 'quietLeader'},
  {title: 'Shaper', value: 'shaper'},
  {title: 'Strategist', value: 'strategist'},
  {title: 'Technician', value: 'technician'},
  {title: 'Thinker', value: 'thinker'},
]