export const PRINCIPLES_YOU_ARCHETYPES = [
  { id: "adventurer", label: "Adventurer" },
  { id: "artisan", label: "Artisan" },
  { id: "campaigner", label: "Campaigner" },
  { id: "coach", label: "Coach" },
  { id: "commander", label: "Commander" },
  { id: "critic", label: "Critic" },
  { id: "enforcer", label: "Enforcer" },
  { id: "entertainer", label: "Entertainer" },
  { id: "explorer", label: "Explorer" },
  { id: "growthSeeker", label: "Growth Seeker" },
  { id: "helper", label: "Helper" },
  { id: "implementer", label: "Implementer" },
  { id: "impresario", label: "Impresario" },
  { id: "individualist", label: "Individualist" },
  { id: "inspirer", label: "Inspirer" },
  { id: "inventor", label: "Inventor" },
  { id: "investigator", label: "Investigator" },
  { id: "orchestrator", label: "Orchestrator" },
  { id: "peacekeeper", label: "Peacekeeper" },
  { id: "planner", label: "Planner" },
  { id: "problemSolver", label: "Problem Solver" },
  { id: "promoter", label: "Promoter" },
  { id: "protector", label: "Protector" },
  { id: "quietLeader", label: "Quiet Leader" },
  { id: "shaper", label: "Shaper" },
  { id: "strategist", label: "Strategist" },
  { id: "technician", label: "Technician" },
  { id: "thinker", label: "Thinker" },
] as const;